"""v8 release safety: a persisted allocation summary generated under a different (older) prompt version is NEVER shown or exported as current intelligence, on any surface; the stored row is
preserved untouched and nothing regenerates it. Residual-era narrative (the v8 prompt gave the model a residual figure) therefore cannot appear after the v8 release."""
from __future__ import annotations

import csv
import io
import re
from pathlib import Path

from sqlalchemy import select

from app.db.models import AllocationIntelligenceSummary
from app.reporting import allocation_intelligence_summary as ais
from app.reporting.allocation_report import build_allocation_report_context, to_csv_bytes, to_csv_rows
from tests.test_allocation_report import _make_allocation, _make_local_plan, _make_summary
from tests.test_allocation_report_pdf import _pdf_text
from app.reporting.allocation_report_pdf import render_allocation_report_pdf

ROOT = Path(__file__).resolve().parents[1]
RESIDUAL_ERA = "Approximately 400 homes of indicative residual capacity remain unaccounted for, an apparent opportunity."
OLD_VERSIONS = ("allocation-intelligence-summary-v8", "allocation-intelligence-summary-v7", None, "")


def _setup(session, prompt_version):
    plan = _make_local_plan(session)
    allocation = _make_allocation(session, plan.id, minimum_dwellings=1000)
    row = _make_summary(session, allocation.id, headline="Large allocation with scope remaining.", overview=RESIDUAL_ERA,
                        key_points='["400 homes of residual capacity"]', prompt_version=prompt_version)
    return allocation, row


def test_helper_flags_only_a_displayed_narrative_from_another_prompt_version():
    from types import SimpleNamespace as S
    assert ais.summary_requires_refresh(S(headline="H", prompt_version=ais.PROMPT_VERSION)) is False
    for version in OLD_VERSIONS:
        assert ais.summary_requires_refresh(S(headline="H", prompt_version=version)) is True
    assert ais.summary_requires_refresh(S(headline=None, prompt_version="allocation-intelligence-summary-v8")) is False       # no narrative: absent, not stale
    assert ais.summary_requires_refresh(None) is False
    assert ais.AI_SUMMARY_REQUIRES_REFRESH_TEXT == "AI summary requires refresh."


def test_report_context_csv_and_pdf_never_carry_a_stale_narrative(session):
    allocation, row = _setup(session, "allocation-intelligence-summary-v8")
    context = build_allocation_report_context(session, [allocation.id])
    ai = context.entries[0].ai_intelligence
    assert ai.available is False and ai.requires_refresh is True and ai.headline is None and ai.overview is None and not ai.key_points
    csv_row = to_csv_rows(context)[0]
    assert csv_row["AI Intelligence Headline"] == "" and csv_row["AI Summary Available"] == "Requires refresh"
    rendered_csv = to_csv_bytes(context).decode("utf-8")
    for narrative in ("400 homes", "indicative residual capacity", "unaccounted for", "an apparent opportunity", "Large allocation with scope remaining"):
        assert narrative not in rendered_csv, narrative
    assert list(csv.DictReader(io.StringIO(rendered_csv)))[0]["AI Summary Available"] == "Requires refresh"
    text = _pdf_text(render_allocation_report_pdf(context))
    assert "AI summary requires refresh." in text and "indicative residual capacity" not in text.lower() and "Large allocation with scope remaining" not in text
    assert "not yet generated" not in text.lower() or "AI summary requires refresh." in text


def test_a_narrative_from_every_non_current_prompt_version_is_suppressed_and_the_current_one_is_shown(session):
    plan = _make_local_plan(session)
    shown = {}
    for index, version in enumerate((*OLD_VERSIONS, ais.PROMPT_VERSION)):
        allocation = _make_allocation(session, plan.id, policy_reference=f"HOM {index}", site_name=f"Alloc {index}", minimum_dwellings=100 + index)
        _make_summary(session, allocation.id, headline=f"Headline {index}", overview=f"Overview {index}", prompt_version=version)
        shown[allocation.id] = version
    context = build_allocation_report_context(session, list(shown))
    for entry in context.entries:
        version = shown[entry.allocation_id]
        assert entry.ai_intelligence.available is (version == ais.PROMPT_VERSION)
        assert entry.ai_intelligence.requires_refresh is (version != ais.PROMPT_VERSION)
        assert (entry.ai_intelligence.headline is not None) is (version == ais.PROMPT_VERSION)


def test_the_stored_row_is_preserved_and_nothing_regenerates_it(session, monkeypatch):
    allocation, row = _setup(session, "allocation-intelligence-summary-v8")
    for name in ("generate_allocation_intelligence_summary",):
        monkeypatch.setattr(ais, name, lambda *a, **k: (_ for _ in ()).throw(AssertionError("a stale summary must never be regenerated by presentation")), raising=False)
    session.expire_all()
    before = {c.key: getattr(session.execute(select(AllocationIntelligenceSummary)).scalar_one(), c.key) for c in AllocationIntelligenceSummary.__table__.columns}
    build_allocation_report_context(session, [allocation.id])
    session.expire_all()
    after_row = session.execute(select(AllocationIntelligenceSummary)).scalar_one()
    assert {c.key: getattr(after_row, c.key) for c in AllocationIntelligenceSummary.__table__.columns} == before          # untouched, headline and all
    assert session.query(AllocationIntelligenceSummary).count() == 1


def test_the_two_pages_show_the_neutral_state_before_any_stored_narrative():
    plans = (ROOT / "app/ui/pages/3_Local_Plan_Sites.py").read_text(encoding="utf-8")
    refresh = plans.index("if summary_requires_refresh(ai_summary_row):")
    narrative = plans.index("ai_summary_row.headline}**")
    assert refresh < narrative and "AI_SUMMARY_REQUIRES_REFRESH_TEXT" in plans[refresh:narrative]
    branch = plans[refresh:plans.index("elif ai_summary_row is not None and ai_summary_row.headline:")]
    assert not re.search(r"ai_summary_row\.(headline|overview|key_points|key_uncertainties|investigation_priorities)", branch)       # the refresh branch never reads the stale text
    shortlist = (ROOT / "app/ui/pages/3b_Shortlist.py").read_text(encoding="utf-8")
    assert "entry.ai_intelligence.requires_refresh" in shortlist and shortlist.index("requires_refresh") > shortlist.index("entry.ai_intelligence.available")


def test_no_other_surface_reads_the_persisted_narrative_fields_directly():
    allowed = {"app/reporting/allocation_intelligence_summary.py", "app/reporting/allocation_report.py", "app/ui/pages/3_Local_Plan_Sites.py", "scripts/preview_ai_summary_staleness.py",
               "scripts/generate_allocation_intelligence_summaries.py", "app/pipeline/run_weekly.py", "app/db/models.py"}
    offenders = []
    for path in list((ROOT / "app").rglob("*.py")) + list((ROOT / "scripts").rglob("*.py")):
        relative = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding="utf-8", errors="ignore")
        if re.search(r"summary(_row)?\.(overview|key_points|key_uncertainties|investigation_priorities)\b", text) and relative not in allowed:
            offenders.append(relative)
    assert offenders == []
